/* assemble.mjs — regenerate the published kit bundles from their source parts.

   Each bundle (docs/v1/sinkaberg-docs.css, app/v1/sinkaberg-app.css) is
   GENERATED, never hand-edited. It is the one file consuming documents/apps
   hotlink; contributors edit the source parts below and re-run this to
   rebuild it. There is no build step for CONSUMERS — they only ever link the
   built bundle — this is a dev/contributor step, the same carve-out as the
   Playwright render harness.

   Both kits share the same layer order on top of the brand foundation:
     1. FONTS      <kit>/parts/fonts.css      @font-face (served next to the bundle)
     2. TOKENS     brand/colors_and_type.css  :root variables + .t-* type scale  ← /design-sync writes this
     3. COMPONENTS brand/components.css       shared component vocabulary
     4. ELEMENTS   <kit>/parts/elements.css   elements added for the kit
     5. PAGE       <kit>/parts/page.css       layout shell + kit-specific page chrome

   Usage:
     node tools/assemble.mjs           rebuild every kit's bundle
     node tools/assemble.mjs --check   exit 1 if any committed bundle is stale */

import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

// Each kit's header is a fixed string — not derived from `parts` — so an
// unrelated kit's build never perturbs another kit's committed bundle bytes.
const DOCS_HEADER = `/* ============================================================
   SINKABERG DOCS KIT — one stylesheet for a repo of documents.
   Link it once per page:  <link rel="stylesheet" href="../sinkaberg-docs.css">
   (adjust the relative path to wherever this file sits).

   GENERATED by tools/assemble.mjs from source parts — do not edit here.
   Edit the sources and re-run \`npm run assemble\`:
     1. FONTS      docs/v1/parts/fonts.css
     2. TOKENS     brand/colors_and_type.css   (/design-sync writes this)
     3. COMPONENTS brand/components.css
     4. ELEMENTS   docs/v1/parts/elements.css
     5. PAGE       docs/v1/parts/page.css
   Everything below uses var(--token) only — no raw hex in components/pages.
   ============================================================ */`;

const APP_HEADER = `/* ============================================================
   SINKABERG APP KIT — one stylesheet for a server-rendered app page.
   Link it once per page:  <link rel="stylesheet" href="../sinkaberg-app.css">
   (adjust the relative path to wherever this file sits).

   GENERATED by tools/assemble.mjs from source parts — do not edit here.
   Edit the sources and re-run \`npm run assemble\`:
     1. FONTS      app/v1/parts/fonts.css
     2. TOKENS     brand/colors_and_type.css   (/design-sync writes this)
     3. COMPONENTS brand/components.css
     4. ELEMENTS   app/v1/parts/elements.css
     5. PAGE       app/v1/parts/page.css
   Everything below uses var(--token) only — no raw hex in components/pages.
   ============================================================ */`;

const bannerBlock = (text) =>
  `/* ============================================================\n   ${text}\n   ============================================================ */`;

/** One entry per published kit. `parts` are bundled in order under `header`. */
export const KITS = [
  {
    name: "docs",
    bundle: "docs/v1/sinkaberg-docs.css",
    header: DOCS_HEADER,
    parts: [
      { banner: null, file: "docs/v1/parts/fonts.css" },
      { banner: "1–2 · TOKEN LAYER — :root variables + .t-* type scale", file: "brand/colors_and_type.css" },
      { banner: "3 · COMPONENT LAYER — shared component vocabulary", file: "brand/components.css" },
      { banner: "4 · ELEMENT LAYER — doc elements added for the kit", file: "docs/v1/parts/elements.css" },
      { banner: "5 · PAGE LAYER — layout shell + index grid + helpers", file: "docs/v1/parts/page.css" },
    ],
  },
  {
    name: "app",
    bundle: "app/v1/sinkaberg-app.css",
    header: APP_HEADER,
    parts: [
      { banner: null, file: "app/v1/parts/fonts.css" },
      { banner: "1–2 · TOKEN LAYER — :root variables + .t-* type scale", file: "brand/colors_and_type.css" },
      { banner: "3 · COMPONENT LAYER — shared component vocabulary", file: "brand/components.css" },
      { banner: "4 · ELEMENT LAYER — app elements added for the kit", file: "app/v1/parts/elements.css" },
      { banner: "5 · PAGE LAYER — layout shell + style-guide catalog + print", file: "app/v1/parts/page.css" },
    ],
  },
];

/** Build one kit's bundle text from its source parts. */
export function assemble(kit) {
  const blocks = [kit.header];
  for (const { banner, file } of kit.parts) {
    const body = readFileSync(join(ROOT, file), "utf8").replace(/\s+$/, "");
    blocks.push((banner ? bannerBlock(banner) + "\n" : "") + body);
  }
  return blocks.join("\n\n") + "\n";
}

/** Absolute path to a kit's committed bundle file. */
export function bundlePath(kit) {
  return join(ROOT, kit.bundle);
}

// Back-compat: the original single-kit API, still used by anything that only
// ever cared about the docs kit's bundle.
export const BUNDLE = bundlePath(KITS[0]);
export const assembleDocs = () => assemble(KITS[0]);

function main() {
  const check = process.argv.includes("--check");
  let stale = 0;
  for (const kit of KITS) {
    const out = assemble(kit);
    const path = bundlePath(kit);
    if (check) {
      const current = readFileSync(path, "utf8");
      if (current !== out) {
        console.error(`assemble: ${kit.bundle} is stale — run \`npm run assemble\`.`);
        stale += 1;
      } else {
        console.log(`assemble: ${kit.bundle} is up to date.`);
      }
    } else {
      writeFileSync(path, out);
      console.log(`assemble: wrote ${kit.bundle}`);
    }
  }
  if (check && stale > 0) process.exitCode = 1;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
