/* assemble.mjs — regenerate the published docs-kit bundle from its source parts.

   The bundle docs/v1/sinkaberg-docs.css is GENERATED, never hand-edited. It is
   the one file consuming documents hotlink; contributors edit the source parts
   below and re-run this to rebuild it. There is no build step for CONSUMERS —
   they only ever link the built bundle — this is a dev/contributor step, the
   same carve-out as the Playwright render harness.

   Sources, in bundle order:
     1. FONTS      docs/v1/parts/fonts.css     @font-face (served next to the bundle)
     2. TOKENS     brand/colors_and_type.css   :root variables + .t-* type scale  ← /design-sync writes this
     3. COMPONENTS brand/components.css         shared component vocabulary
     4. ELEMENTS   docs/v1/parts/elements.css   doc elements added for the kit
     5. PAGE       docs/v1/parts/page.css       layout shell, index grid, print

   Usage:
     node tools/assemble.mjs           rebuild docs/v1/sinkaberg-docs.css
     node tools/assemble.mjs --check   exit 1 if the committed bundle is stale */

import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
export const BUNDLE = join(ROOT, "docs/v1/sinkaberg-docs.css");

const HEADER = `/* ============================================================
   SINKABERG DOCS KIT — one stylesheet for a repo of documents.
   Link it once per page:  <link rel="stylesheet" href="../sinkaberg-docs.css">
   (adjust the relative path to wherever this file sits).

   GENERATED by tools/assemble.mjs from source parts — do not edit here.
   Edit the sources and re-run \`npm run assemble\`:
     1. FONTS      docs/v1/parts/fonts.css
     2. TOKENS     brand/colors_and_type.css   (/design-sync writes this)
     3. COMPONENTS brand/components.css
     4. ELEMENTS   docs/v1/parts/elements.css
     5. PAGE       docs/v1/parts/page.css
   Everything below uses var(--token) only — no raw hex in components/pages.
   ============================================================ */`;

/** ordered source parts; `banner` labels the layer in the built file. */
const PARTS = [
  { banner: null, file: "docs/v1/parts/fonts.css" },
  { banner: "1–2 · TOKEN LAYER — :root variables + .t-* type scale", file: "brand/colors_and_type.css" },
  { banner: "3 · COMPONENT LAYER — shared component vocabulary", file: "brand/components.css" },
  { banner: "4 · ELEMENT LAYER — doc elements added for the kit", file: "docs/v1/parts/elements.css" },
  { banner: "5 · PAGE LAYER — layout shell + index grid + helpers", file: "docs/v1/parts/page.css" },
];

const bannerBlock = (text) =>
  `/* ============================================================\n   ${text}\n   ============================================================ */`;

/** Build the bundle text from the source parts. */
export function assemble() {
  const blocks = [HEADER];
  for (const { banner, file } of PARTS) {
    const body = readFileSync(join(ROOT, file), "utf8").replace(/\s+$/, "");
    blocks.push((banner ? bannerBlock(banner) + "\n" : "") + body);
  }
  return blocks.join("\n\n") + "\n";
}

function main() {
  const out = assemble();
  if (process.argv.includes("--check")) {
    const current = readFileSync(BUNDLE, "utf8");
    if (current !== out) {
      console.error("assemble: docs/v1/sinkaberg-docs.css is stale — run `npm run assemble`.");
      process.exitCode = 1;
    } else {
      console.log("assemble: bundle is up to date.");
    }
    return;
  }
  writeFileSync(BUNDLE, out);
  console.log("assemble: wrote docs/v1/sinkaberg-docs.css");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
